config/routes.rb
Rails.application.routes.draw do
  get 'orders/new'
  get 'relationships/create'
  get 'reviews/new'
  get 'reviews/create'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "books#index"
  get "/books", to: "books#index", as: "books"
  get "/books/new", to: "books#new", as: "new_book"
  post "/books", to: "books#create"
  get "/books/add", to: "books#add", as: "add_book_to_list"
  delete "books/:id", to: "book_list_items#destroy"
  get "/books/:id", to: "books#show", as: "book"
  get "/authors", to: "authors#index", as: "authors"
  get "/authors/:id", to: "authors#show", as: "author"
  get "/mylist", to: "book_list_items#index", as: "book_list_items"
  get "/mylist/:id/edit", to: "book_list_items#edit", as: "edit_book_list_item"
  put "/mylist/:id", to: "book_list_items#update"
  patch "/mylist/:id", to: "book_list_items#update", as: "book_list_item"
  get "/reviews/new", to: "reviews#new", as: "new_review"
  post "reviews", to: "reviews#create"
  post "follow/:user_id", to: "relationships#create", as: "follow_user"
  
  get "orders", to: "orders#new", as: "new_order"
  # resources :orders, only: [:new, :show]
end

app/models/book_list_item.rb
class BookListItem < ApplicationRecord
  belongs_to :user
  belongs_to :book

  def self.books_for_current_user(current_user)
    return current_user.books
    # return BookListItem.where(user_id: current_user.id).order(:updated_at)
  end

  def self.contains?(current_user, book)
    return current_user.books.where(id: book.id).length > 0
  end

  def self.create_book_list_item(current_user,book)
    if (current_user.books.where(id: book.id).length == 0)
      current_user.books.push(book)
      current_user.save
    end
  end
 
  def self.book_list_item_id(current_user,book)
    return BookListItem.where("book_id = ? AND user_id = ?", book,current_user.id).first.id
  end
end

app/controllers/book_list_items_controller.rb
class BookListItemsController < ApplicationController
    before_action :authenticate_user!
    def index
        @books = current_user.books
    end

    def destroy
        item_id = BookListItem.book_list_item_id(current_user,params[:id])
        BookListItem.destroy(item_id)
        redirect_to book_list_items_path
    end

    # def destroy
    #     # .where returns an array (even with only one result) hence we use .first
    #     BookListItem.where(book_id: params[:book_id], user_id: current_user.id).first.destroy
    #     redirect_to book_list_items_path
    # end

    def edit
        @book_list_item = BookListItem.find(BookListItem.book_list_item_id(current_user,params[:id]))
    end

    def update
        book_list_item = BookListItem.find(params[:id])
        available_for_trade = params[:book_list_item][:for_trade]

        # If available_for_trade is "1" set for_trade = true
        if available_for_trade = "1"
            book_list_item.for_trade = true
        else
        # but if available_for_trade is "0" set for_trade = false
            book_list_item.for_trade = false
        end

        if book_list_item.save
            flash[:alert] = "Your changes have been saved"
        else
            flash[:alert] = "There was an error saving your changes"
        end

        redirect_to book_path(book_list_item.book.id)
    end
end

app/helpers/book_list_items_helper.rb
module BookListItemsHelper
end

app/views/book_list_items/edit.html.erb
<h1> Edit <%=@book_list_item.book.title%></h1>
<p><%=@book_list_item.book.author.name%></p>

<%=form_with model: @book_list_item do |form|%>
<p>
   <%=form.check_box :for_trade, value: @book_list_item.for_trade%>
   <%= label :for_trade, "Willing to trade"%>
</p>
<%=form.submit 'Update'%>
<%end%>

app/views/book_list_items/index.html.erb
<h1 class="heading">My List</h1>

<%= link_to 'Add a book', new_book_path%>
<% if @books %>
    <% @books&.each do |book|%>
    <p class="book-item">
        <%= link_to book.title, book_path(book) %>
        <%= link_to book.author.name, author_path(book.author) %>
    </p>
    <%end%>
<%end%>

<h2 class="list-item">You are following <%= current_user.following.length %> users</h2>
<ul>
    <% current_user.following.each do |user| %>
    <li class="list-item">
        <%= user.name %>
    </li>
    <% end %>
</ul>