config/routes.rb
Rails.application.routes.draw do
  get 'orders/new'
  get 'relationships/create'
  get 'reviews/new'
  get 'reviews/create'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "books#index"
  get "/books", to: "books#index", as: "books"
  get "/books/new", to: "books#new", as: "new_book"
  post "/books", to: "books#create"
  get "/books/add", to: "books#add", as: "add_book_to_list"
  delete "books/:id", to: "book_list_items#destroy"
  get "/books/:id", to: "books#show", as: "book"
  get "/authors", to: "authors#index", as: "authors"
  get "/authors/:id", to: "authors#show", as: "author"
  get "/mylist", to: "book_list_items#index", as: "book_list_items"
  get "/mylist/:id/edit", to: "book_list_items#edit", as: "edit_book_list_item"
  put "/mylist/:id", to: "book_list_items#update"
  patch "/mylist/:id", to: "book_list_items#update", as: "book_list_item"
  get "/reviews/new", to: "reviews#new", as: "new_review"
  post "reviews", to: "reviews#create"
  post "follow/:user_id", to: "relationships#create", as: "follow_user"
  
  get "orders", to: "orders#new", as: "new_order"
  # resources :orders, only: [:new, :show]
end

app/views/shared/_sidenav.html.erb
<nav class="header">
    <%if user_signed_in?%>
    <%=link_to 'My List', book_list_items_path, class: "nav-link"%>
    <%=link_to 'Books', books_path, class: "nav-link" %>
    <%=link_to 'Authors', authors_path, class: "nav-link"%>
    <%end%>
</nav>

app/views/shared/_topnav.html.erb
<section class="header">
    <% if user_signed_in? %>
        <div id="logout"><%= link_to 'Logout', destroy_user_session_path, method: "delete",class:"top-nav-link"%></div>
        <div id="username"><%= current_user.name %></div>
    <% else %>
        <p><%= link_to 'Login', new_user_session_path, class:"top-nav-link"%>
        |
        <%= link_to 'Sign Up', new_user_registration_path, class:"top-nav-link"%>
        </p>
    <% end %>
</section>