config/routes.rb
Rails.application.routes.draw do
  get 'orders/new'
  get 'relationships/create'
  get 'reviews/new'
  get 'reviews/create'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "books#index"
  get "/books", to: "books#index", as: "books"
  get "/books/new", to: "books#new", as: "new_book"
  post "/books", to: "books#create"
  get "/books/add", to: "books#add", as: "add_book_to_list"
  delete "books/:id", to: "book_list_items#destroy"
  get "/books/:id", to: "books#show", as: "book"
  get "/authors", to: "authors#index", as: "authors"
  get "/authors/:id", to: "authors#show", as: "author"
  get "/mylist", to: "book_list_items#index", as: "book_list_items"
  get "/mylist/:id/edit", to: "book_list_items#edit", as: "edit_book_list_item"
  put "/mylist/:id", to: "book_list_items#update"
  patch "/mylist/:id", to: "book_list_items#update", as: "book_list_item"
  get "/reviews/new", to: "reviews#new", as: "new_review"
  post "reviews", to: "reviews#create"
  post "follow/:user_id", to: "relationships#create", as: "follow_user"
  
  get "orders", to: "orders#new", as: "new_order"
  # resources :orders, only: [:new, :show]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :book_list_items
  has_many :users, through: :book_list_items
  has_many :reviews
  has_one_attached :cover

  validates :title, presence: true
  validates :genre, inclusion: { in: ["Romance", "SciFi", "Drama"]}

  def self.ordered_by_author_and_title
    books = []
    Author.all.order(:last_name).each do |author|
      books += author.books.order(:title)
    end
    return books
  end

  def self.find_book(title, author_last_name)
    belongs_to :author
    has_many :book_list_items
    has_many :reviews
    
    book = nil
    books = Book.where("LOWER(title) = ?", title.downcase.strip)
    if (books)
      book = books.first
      if (book && book.author.last_name.downcase != author_last_name.downcase.strip)
        book = nil
      end
    end
    return book
  end

  def self.create_book(title, author, genre, price)
    book = Book.find_book(title, author.last_name)
    if(!book)
      book = Book.new(title: title, genre: genre, author_id: author.id, price: price)
      book.save
    end
    return book
  end

  def author_name
    return "#{author.first_name} #{author.last_name}"
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @books = Book.ordered_by_author_and_title
    end

    def show
        @book = Book.find(params[:id])
        @can_add = !BookListItem.contains?(current_user,@book) if user_signed_in?
        @reviews = @book.reviews
        @rating = Review.get_average_rating(@book)
    end

    def new
        @book = Book.new
    end

    def create
        author = Author.create_author(params[:book][:first_name], params[:book][:last_name])
        @book = Book.new(book_params)
        @book.author = author
        @book.cover.attach(params[:book][:cover])
        
        if @book.valid?
            BookListItem.create_book_list_item(current_user, @book)
            redirect_to book_list_items_path
        else
            render "new"
        end

        @book.cover.attach(params[:book][:cover])
    end

    def book_params
        params.require(:book).permit(:title, :genre, :price)
    end
    
    def add
        book = Book.find(params[:id])

        if BookListItem.contains?(current_user, book)
            flash[:alert] = "Sorry, that book is already in your list"
            redirect_to book_path(book.id)
        else
            current_user.books.push(book)
            if current_user.save
                flash[:alert] = "We have added #{book.title} in your list."
                redirect_to book_list_items_path
            else
                flash[:alert] = "Oops! There was a problem adding that book"
            end
        end
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<h1>Books</h1>
<%if @books%>
    <% @books.each do |book|%>
        <p><%=link_to book.title, book_path(book) %></p>
        <p><%=link_to book.author.name, author_path(book.author) %></p>
    <%end%>
<%end%>

app/views/books/new.html.erb
<% if @book.errors.any? %>
    <p>
        <%= @book.errors.full_messages.join() %>
    </p>
<%end%>

<%=form_with model: @book, local: true do |form|%>
    <p>
        <%=label(:title, 'Title')%>
        <%= form.text_field :title, required: true, minlength: 1%>
    </p>
    <p>
        <%=label(:genre, 'Genre')%>
        <%= form.select :genre, options_for_select(["Please choose...", "Romance", "Drama", "SciFi", "Memoir"])%>
    
    <p>Author</p>
    <p>   
        <%=label(:first_name, 'First Name')%>
        <%= form.text_field :first_name%>
        <%=label(:last_name, 'Last Name')%>
        <%= form.text_field :last_name, required: true, minlength: 1%>
    </p>

    <p>
        <%= form.label :cover %>
        <%= form.file_field :cover %>
    </p>
    <p>
        <%= form.label :price %>
        <%= form.number_field :price, step: :any %>
    </p>

    <%= form.submit "Add book", class: "button"%>
<%end%>

app/views/books/show.html.erb
<h1 class="heading"><%=@book.title%></h1>

<% if @book.cover.attached? %>
  <p class="book-item">
    <%= image_tag @book.cover, width: 120 %>
  </p>
<% end %>

<p><%=@book.author.name%></p>
<p><%=@book.genre%></p>
<% if @book.price %>
  <p class="list-item">
  <%= number_to_currency @book.price %>
  <%= link_to "Buy now", new_order_path(book_id: @book.id) %>
  </p>
<% end %>

<% if user_signed_in? %>
    <%if @can_add %>
      <p class="link book-item"> <%= link_to 'Add to my list', add_book_to_list_path(:id => @book)%></p>
    <%else%>
      <p class="link book-item"> <%= link_to 'Remove from my list', @book, method: "delete"%></p>
    <%end%>
    <p>
      <%= link_to "Edit book", edit_book_list_item_path(id: @book.id) %>
      <%= link_to 'Add a review', new_review_path(book: @book)%>
    </p>
<%end%>

<div>
 <h1>Reviews</h1>
 <%if @reviews%>
   <%@reviews.each do |review|%>
     <div>
      <p class="rating"><%= "Rating: #{review.rating}"%></p>
      <p><%= review.user.email%></p>
      <p><%= review.comment %></p>
     </div>
   <%end%>
 <%end%>
</div>

<div class="list-item">
  <h1><%= pluralize @book.users.length, "user" %> have this book listed</h1>
  <ul class="list-item">
    <% @book.users.each do |user| %>
    <li class="list-item"><%= user.name %>
      <% if current_user != nil && user != current_user %>
        <%= form_with url: follow_user_path(user_id: user.id), local: true do |form| %>
          <%= form.submit "Follow" %>
        <% end %>
      <% end %>
    </li>
    <% end %>
  </ul>
</div>

<p><%=link_to 'Back', :back %></p>